// State
const state = {
  files: [],        // { path, name, size }
  index: 0,
  marked: new Set(),   // indices marked for deletion
  history: [],         // stack of { index, wasMarked } for undo
  scriptSaved: false,
  cache: new Map(),    // path -> data URL
  cacheOrder: [],
};

const PRELOAD = 3; // number of images to preload ahead

// DOM refs
const startScreen   = document.getElementById('start-screen');
const sortScreen    = document.getElementById('sort-screen');
const finishScreen  = document.getElementById('finish-screen');
const openFolderBtn = document.getElementById('open-folder-btn');
const mainImg       = document.getElementById('main-img');
const deleteBadge   = document.getElementById('delete-badge');
const progressFill  = document.getElementById('progress-bar-fill');
const progressText  = document.getElementById('progress-text');
const filenameLbl   = document.getElementById('filename');
const filesizeLbl   = document.getElementById('filesize');
const btnDelete     = document.getElementById('btn-delete');
const btnKeep       = document.getElementById('btn-keep');
const btnUndo       = document.getElementById('btn-undo');
const btnPrev       = document.getElementById('btn-prev');
const btnNext       = document.getElementById('btn-next');
const statTotal     = document.getElementById('stat-total');
const statDelete    = document.getElementById('stat-delete');
const statKeep      = document.getElementById('stat-keep');
const scriptPreview = document.getElementById('script-preview');
const btnCopyScript = document.getElementById('btn-copy-script');
const btnSaveScript = document.getElementById('btn-save-script');
const btnNewSession = document.getElementById('btn-new-session');
const copyConfirm   = document.getElementById('copy-confirm');

// ── Helpers ────────────────────────────────────────────────────────────────

function fmt(bytes) {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / 1048576).toFixed(1) + ' MB';
}

function show(screen) {
  [startScreen, sortScreen, finishScreen].forEach(s => s.classList.remove('active'));
  screen.classList.add('active');
}

async function loadImageCached(path) {
  if (state.cache.has(path)) return state.cache.get(path);
  const data = await window.api.readImage(path);
  state.cache.set(path, data);
  state.cacheOrder.push(path);
  // Keep cache bounded to ~20 entries
  while (state.cacheOrder.length > 20) {
    const old = state.cacheOrder.shift();
    state.cache.delete(old);
  }
  return data;
}

function preload(fromIndex) {
  for (let i = 1; i <= PRELOAD; i++) {
    const idx = fromIndex + i;
    if (idx < state.files.length) {
      loadImageCached(state.files[idx].path).catch(() => {});
    }
  }
}

async function showPhoto(index) {
  if (state.files.length === 0) return;
  state.index = index;

  const file = state.files[index];
  filenameLbl.textContent = file.name;
  filesizeLbl.textContent = fmt(file.size);

  mainImg.classList.add('loading');
  try {
    const data = await loadImageCached(file.path);
    mainImg.src = data;
  } catch {
    mainImg.src = '';
  }
  mainImg.classList.remove('loading');

  deleteBadge.classList.toggle('visible', state.marked.has(index));
  updateProgress();
  preload(index);
}

function updateProgress() {
  const total = state.files.length;
  const pct = total > 0 ? ((state.index + 1) / total) * 100 : 0;
  progressFill.style.width = pct + '%';
  progressText.textContent = `${state.index + 1} / ${total}`;
  btnPrev.disabled = state.index === 0;
  btnNext.disabled = state.index === state.files.length - 1;
}

function buildScript() {
  if (state.marked.size === 0) return '#!/bin/bash\n# No files marked for deletion.';
  const lines = ['#!/bin/bash', '# Generated by PhotoSort', '# Review carefully before running!', ''];
  [...state.marked]
    .sort((a, b) => a - b)
    .forEach(i => {
      const p = state.files[i].path.replace(/'/g, "'\\''");
      lines.push(`rm '${p}'`);
    });
  return lines.join('\n');
}

// ── Actions ────────────────────────────────────────────────────────────────

function markDelete() {
  const i = state.index;
  const wasMarked = state.marked.has(i);
  state.history.push({ index: i, wasMarked });

  if (wasMarked) {
    state.marked.delete(i);
  } else {
    state.marked.add(i);
  }

  deleteBadge.classList.toggle('visible', state.marked.has(i));
  advance(1);
}

function markKeep() {
  const i = state.index;
  const wasMarked = state.marked.has(i);
  state.history.push({ index: i, wasMarked });
  // Keep = ensure NOT marked
  state.marked.delete(i);
  advance(1);
}

function undo() {
  if (state.history.length === 0) return;
  const { index, wasMarked } = state.history.pop();
  if (wasMarked) state.marked.add(index);
  else state.marked.delete(index);
  showPhoto(index);
}

function advance(dir) {
  const next = state.index + dir;
  if (next < 0) return;
  if (next >= state.files.length) {
    finish();
    return;
  }
  showPhoto(next);
}

function finish() {
  state.scriptSaved = false;
  statTotal.textContent = state.files.length;
  statDelete.textContent = state.marked.size;
  statKeep.textContent = state.files.length - state.marked.size;
  scriptPreview.textContent = buildScript();
  show(finishScreen);
}

// ── Event wiring ───────────────────────────────────────────────────────────

openFolderBtn.addEventListener('click', async () => {
  const folder = await window.api.pickFolder();
  if (!folder) return;
  const files = await window.api.readFolder(folder);
  if (files.length === 0) {
    alert('No supported image files found in that folder.');
    return;
  }
  state.files = files;
  state.index = 0;
  state.marked.clear();
  state.history.length = 0;
  state.cache.clear();
  state.cacheOrder.length = 0;
  state.scriptSaved = false;
  show(sortScreen);
  await showPhoto(0);
});

btnDelete.addEventListener('click', markDelete);
btnKeep.addEventListener('click', markKeep);
btnUndo.addEventListener('click', undo);
btnPrev.addEventListener('click', () => advance(-1));
btnNext.addEventListener('click', () => advance(1));

let lastKeyAction = 0;
const KEY_REPEAT_MS = 80; // minimum ms between repeat fires

document.addEventListener('keydown', (e) => {
  if (!sortScreen.classList.contains('active')) return;
  const now = Date.now();
  switch (e.key) {
    case 'ArrowLeft':
    case 'a': case 'A':
      if (e.repeat && now - lastKeyAction < KEY_REPEAT_MS) return;
      lastKeyAction = now;
      markDelete(); break;
    case 'ArrowRight':
    case 'd': case 'D':
      if (e.repeat && now - lastKeyAction < KEY_REPEAT_MS) return;
      lastKeyAction = now;
      markKeep(); break;
    case 'z': case 'Z':
      if (e.repeat) return; // undo stays single-fire
      undo(); break;
  }
});

// Title bar controls
document.getElementById('btn-min').addEventListener('click', () => window.api.minimizeWindow());
document.getElementById('btn-max').addEventListener('click', () => window.api.maximizeWindow());
document.getElementById('btn-close').addEventListener('click', () => window.api.closeWindow());

// Finish screen
btnCopyScript.addEventListener('click', async () => {
  await window.api.copyScript(buildScript());
  state.scriptSaved = true;
  copyConfirm.classList.remove('hidden');
  setTimeout(() => copyConfirm.classList.add('hidden'), 2000);
});

btnSaveScript.addEventListener('click', async () => {
  const saved = await window.api.saveScript(buildScript());
  if (saved) {
    state.scriptSaved = true;
    copyConfirm.textContent = 'Script saved!';
    copyConfirm.classList.remove('hidden');
    setTimeout(() => {
      copyConfirm.classList.add('hidden');
      copyConfirm.textContent = 'Copied to clipboard!';
    }, 2000);
  }
});

btnNewSession.addEventListener('click', () => {
  if (state.marked.size > 0 && !state.scriptSaved) {
    const ok = confirm(
      `You have ${state.marked.size} file(s) marked for deletion but haven't saved or copied the script yet.\n\nStart a new session anyway? The list will be lost.`
    );
    if (!ok) return;
  }
  state.files = [];
  state.marked.clear();
  state.history.length = 0;
  state.cache.clear();
  state.cacheOrder.length = 0;
  show(startScreen);
});
